--- output/build/osm-scout-server-1.17.0/Makefile	2020-09-12 19:10:52.084610475 -0400
+++ output/build/osm-scout-server-1.17.0/Makefile.changed	2020-09-12 19:12:47.385255818 -0400
@@ -40,7 +40,8 @@
 DISTDIR = /home/brad/Projects/buildroot/output/build/osm-scout-server-1.17.0/.tmp/osmscout-server1.17.0
 LINK          = /home/brad/Projects/buildroot/output/host/bin/arm-buildroot-linux-gnueabihf-g++
 LFLAGS        = --sysroot=/home/brad/Projects/buildroot/output/host/arm-buildroot-linux-gnueabihf/sysroot -Wl,-O1
-LIBS          = $(SUBLIBS) -latomic -lmicrohttpd -lpostal -losmscout_map_qt -losmscout_map -losmscout -fopenmp -L/usr/local/lib -lmarisa -lkyotocabinet -lsqlite3 -L/home/brad/Projects/buildroot/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib -lvalhalla -lprotobuf-lite -pthread -lcurl -lz -lsystemd /home/brad/Projects/buildroot/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5Gui.so /home/brad/Projects/buildroot/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5Network.so /home/brad/Projects/buildroot/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5Sql.so /home/brad/Projects/buildroot/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5Xml.so /home/brad/Projects/buildroot/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5Positioning.so /home/brad/Projects/buildroot/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5DBus.so /home/brad/Projects/buildroot/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5Core.so -lGLESv2 -lpthread  -lrt -lpthread -ldl 
+LIBS          = $(SUBLIBS) -latomic -lmicrohttpd -lpostal -losmscout_map_qt -losmscout_map -losmscout -fopenmp -lboost_filesystem -lboost_system -lmarisa -lkyotocabinet -lsqlite3 -L/home/brad/Projects/buildroot/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib -lvalhalla -lprotobuf-lite -pthread -lcurl -lz -lsystemd /home/brad/Projects/buildroot/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5Gui.so /home/brad/Projects/buildroot/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5Network.so /home/brad/Projects/buildroot/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5Sql.so /home/brad/Projects/buildroot/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5Xml.so /home/brad/Projects/buildroot/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5Positioning.so /home/brad/Projects/buildroot/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5DBus.so /home/brad/Projects/buildroot/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5Core.so -lGLESv2 -lpthread  -lrt -lpthread -ldl 
+INSTALL_ROOT  = $(PKG_CONFIG_SYSROOT_DIR)
 AR            = /home/brad/Projects/buildroot/output/host/bin/arm-buildroot-linux-gnueabihf-ar cqs
 RANLIB        = 
 SED           = sed
