################################################################################
#
# libfoo
#
################################################################################

LIBOSMSCOUT_VERSION = 5c1e2b408e7622c341c71f913a21acf542611dd6
#LIBOSMSCOUT_SOURCE= $(LIBOSMSCOUT_VERSION).tar.gz
LIBOSMSCOUT_SITE = git://github.com/rinigus/libosmscout.git
LIBOSMSCOUT_INSTALL_STAGING = YES
LIBOSMSCOUT_INSTALL_TARGET = YES
LIBOSMSCOUT_CONF_ENV = 
LIBOSMSCOUT_CONF_OPTS = -DBUILD_WITH_OPENMP=OFF -DOSMSCOUT_BUILD_MAP_OPENGL=OFF -DOSMSCOUT_BUILD_IMPORT=OFF -DOSMSCOUT_BUILD_MAP_AGG=OFF -DOSMSCOUT_BUILD_MAP_CAIRO=OFF -DOSMSCOUT_BUILD_MAP_SVG=OFF -DOSMSCOUT_BUILD_MAP_IOSX=OFF -DOSMSCOUT_BUILD_TESTS=OFF -DOSMSCOUT_BUILD_DEMOS=OFF -DOSMSCOUT_BUILD_BINDING_JAVA=OFF -DOSMSCOUT_BUILD_BINDING_CSHARP=OFF -DOSMSCOUT_BUILD_DOC_API=OFF -DOSMSCOUT_BUILD_CLIENT_QT=ON -DOSMSCOUT_BUILD_TOOL_OSMSCOUT2=OFF -DOSMSCOUT_BUILD_TOOL_STYLEEDITOR=OFF -DGPERFTOOLS_USAGE=OFF -DOSMSCOUT_BUILD_TOOL_IMPORT=OFF -DOSMSCOUT_BUILD_TOOL_DUMPDATA=OFF
LIBOSMSCOUT_DEPENDENCIES = qt5svg protobuf qt5quickcontrols qt5quickcontrols2 qt5base
#LIBOSMSCOUT_GIT_SUBMODULES=YES

$(eval $(cmake-package))
